version: '3.8'

services:
  app:
    image: travel-booking-web-app.cr.cloud.ru/travel-booking-web-app
    container_name: travel-booking-web-app
    network_mode: "host"
    # Build args for NEXT_PUBLIC_* variables (used if building locally)
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      # Application
      - APPLICATION_NAME=${APPLICATION_NAME}
      - DEVELOPED_BY=${DEVELOPED_BY}
      # Database Configuration (подключение к PostgreSQL на хосте)
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=localhost
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      # Next.js Environment
      - NODE_ENV=${NODE_ENV}
      - STAGE=${STAGE}
      # Telegram Bot Configuration
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}
      # JWT Authentication
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - COOKIE_JWT_TTL=${COOKIE_JWT_TTL}
      - COOKIE_REFRESH_JWT_TTL=${COOKIE_REFRESH_JWT_TTL}
      # Prisma Logging Configuration
      - PRISMA_LOG_LEVELS=${PRISMA_LOG_LEVELS}
      # Cloud.ru artifact registry
      - ARTIFACT_REGISTRY_URI=${ARTIFACT_REGISTRY_URI}
      - ARTIFACT_REGISTRY_NAME=${ARTIFACT_REGISTRY_NAME}
      - CLOUD_RU_KEY_ID=${CLOUD_RU_KEY_ID}
      - CLOUD_RU_KEY_SECRET=${CLOUD_RU_KEY_SECRET}
      # Cloud.ru object storage
      - OBJECT_STORAGE_REGION=${OBJECT_STORAGE_REGION}
      - OBJECT_STORAGE_ENDPOINT=${OBJECT_STORAGE_ENDPOINT}
      - OBJECT_STORAGE_BUCKET_NAME=${OBJECT_STORAGE_BUCKET_NAME}
      - OBJECT_STORAGE_BUCKET_ENDPOINT=${OBJECT_STORAGE_BUCKET_ENDPOINT}
      - OBJECT_STORAGE_TENANT_ID=${OBJECT_STORAGE_TENANT_ID}
      # Logger Service Configuration
      - LOGGER_URL=${LOGGER_URL}
      - LOGGER_CHAT_ID=${LOGGER_CHAT_ID}
    env_file:
      - .env
    restart: unless-stopped